#cloud-config
repo_update: true
repo_upgrade: all

packages:
- amazon-efs-utils

runcmd:
- echo ECS_CLUSTER=${ecs_cluster_name} >> /etc/ecs/ecs.config; echo ECS_BACKEND_HOST= >> /etc/ecs/ecs.config
- mkdir -p /mnt/efs
- echo "${efs_filesystem_id}:/ /mnt/efs efs tls,_netdev" >> /etc/fstab
- mount -a -t efs defaults
